### ISSUE TITLE
Project on exFAT partition on Ubuntu > OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by lemariva** [BradenM/micropy-cli#104]
**Describe the bug**
```
lemariva@:~/Documents/work/lemariva.com/Github/MicroPy$ micropy init

MicroPy  Creating New Project
? Project Name MicroPy                                                                                                                              
? Choose any Templates to Generate  [VSCode Settings for Autocompletion/Intellisense]                                                               
? Which stubs would you like to use?  [esp32-micropython-1.12.0]                                                                                    

MicroPy  Initiating MicroPy
MicroPy  Stubs: esp32-micropython-1.12.0
MicroPy  Failed to Create Stub Links!
MicroPy  OSError: [Errno 38] Function not implemented: '/home/lemariva/.micropy/stubs/BradenM-micropy-stubs-27ee48a' -> '/home/lemariva/Documents/work/lemariva.com/Github/MicroPy/.micropy/BradenM-micropy-stubs-27ee48a'
lemariva@l:~/Documents/work/lemariva.com/Github/MicroPy$
```
The problem appears on Ubuntu (20.04 LTS). 
An exFAT partition is mounted on '/home/lemariva/Documents/work/' (encrypted and shared with Windows 10 - that's why exFAT). The exFAT file system does not support soft/hard links. The [line](https://github.com/BradenM/micropy-cli/blob/8ce66868670628821b820070aa5cb4a708ba619e/micropy/utils/helpers.py#L327):
```
source.symlink_to(target, target_is_directory=True)
```
generates the exception.

**Possible Solution**
If the error occurs (errno 38), copy the folders instead of making a link.

**Logs**
```
[2020-05-05 00:15:09] INFO: stubs: esp32-micropython-1.12.0 is already installed!
[2020-05-05 00:15:09] DEBUG: micropy.config.config: added config value [stubs] -> {'esp32-micropython-1.12.0': '1.3.2'}
[2020-05-05 00:15:09] ERROR: micropy: Failed to Create Stub Links!
[2020-05-05 00:15:09] ERROR: micropy: OSError: [Errno 38] Function not implemented: '/home/lemariva/.micropy/stubs/BradenM-micropy-stubs-27ee48a' -> '/home/lemariva/Documents/work/lemariva.com/Github/MicroPy/.micropy/BradenM-micropy-stubs-27ee48a'
Traceback (most recent call last):
  File "/home/lemariva/.local/lib/python3.8/site-packages/micropy/project/modules/stubs.py", line 90, in _resolve_subresource
    resource = set(
  File "/home/lemariva/.local/lib/python3.8/site-packages/micropy/stubs/stubs.py", line 381, in resolve_subresource
    fware = FirmwareStub.resolve_link(fware, link)
  File "/home/lemariva/.local/lib/python3.8/site-packages/micropy/stubs/stubs.py", line 435, in resolve_link
    utils.create_dir_link(link_path, stub.path)
  File "/home/lemariva/.local/lib/python3.8/site-packages/micropy/utils/helpers.py", line 334, in create_dir_link
    raise e
  File "/home/lemariva/.local/lib/python3.8/site-packages/micropy/utils/helpers.py", line 329, in create_dir_link
    source.symlink_to(target, target_is_directory=True)
  File "/usr/lib/python3.8/pathlib.py", line 1374, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.8/pathlib.py", line 442, in symlink
    return os.symlink(a, b)
OSError: [Errno 38] Function not implemented: '/home/lemariva/.micropy/stubs/BradenM-micropy-stubs-27ee48a' -> '/home/lemariva/Documents/work/lemariva.com/Github/MicroPy/.micropy/BradenM-micropy-stubs-27ee48a'
```

**Context (Environment)**
* OS: Ubuntu 20.04 LTS
* Micropy Version: micropy, version 3.3.0
* Python Version: Python 3.8.2
* VSCode Version: 1.45.0-insider

**Comment by BradenM** [comment]
Thanks! Closed by #105
