### ISSUE TITLE
Using under Windows

### ISSUE THREAD

**Issue by hwcconde** [BradenM/micropy-cli#277]
I've installed it using pip in a Windows machine

When executing it always throws:

`Traceback (most recent call last):
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\H354000\AppData\Local\Programs\Python\Python37\Scripts\micropy.exe\__main__.py", line 4, in <module>
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\__init__.py", line 18, in <module>
    from micropy import data, lib, project, stubs, utils
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\project\__init__.py", line 5, in <module>
    from . import modules
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\project\modules\__init__.py", line 7, in <module>
    from .packages import DevPackagesModule, PackagesModule
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\project\modules\packages.py", line 12, in <module>
    from micropy.packages import (
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\packages\__init__.py", line 16, in <module>
    from .source_package import PackageDependencySource, VCSDependencySource
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\micropy\packages\source_package.py", line 9, in <module>
    from git import Repo
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\git\__init__.py", line 8, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\git\exc.py", line 10, in <module>
    from git.compat import safe_decode
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\git\compat.py", line 32, in <module>
    from git.types import TBD
  File "c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\git\types.py", line 12, in <module>
    from typing_extensions import Final, Literal, SupportsIndex  # noqa: F401
ImportError: cannot import name 'SupportsIndex' from 'typing_extensions' (c:\users\h354000\appdata\local\programs\python\python37\lib\site-packages\typing_extensions.py)`

I'm not sure how to solve it...

**Comment by hwcconde** [comment]
I downgraded my install to a version which seemed to work:

> pip install micropy-cli==3.1.1
