### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by bananabr** [BradenM/micropy-cli#295]
**Describe the bug**
There seems to be a dependency issue involving micropy-cli and Jinja 2 when, at least when running on Windows.

**Expected Behavior**
No exception is thrown during normal execution

**Current Behavior**
![image](https://user-images.githubusercontent.com/9096933/161575954-1d003a53-ea57-4cfd-bb66-c32edd8975f2.png)

**Steps to Reproduce**
1. Install the latest version of micropy-cli on a Windows 10 machine running python 3.8
2. Try running micropy-cli

**Logs**
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\danie\appdata\roaming\python\python38\scripts\micropy.exe\__main__.py", line 4, in <module>
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\micropy\__init__.py", line 18, in <module>
    from micropy import data, lib, project, stubs, utils
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\micropy\project\__init__.py", line 5, in <module>
    from . import modules
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\micropy\project\modules\__init__.py", line 9, in <module>
    from .templates import TemplatesModule
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\micropy\project\modules\templates.py", line 7, in <module>
    from micropy.project.template import TemplateProvider
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\micropy\project\template.py", line 11, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\danie\AppData\Roaming\Python\Python38\site-packages\markupsafe\__init__.py)

**Context (Environment)**

Windows 10

Latest

3.8

Not applicable

**Comment by BradenM** [comment]
Hi @bananabr,

Thanks for the report. 
This is actually a known issue and is being addressed in the upcoming v4 release :smile: 

You can install the latest pre-release (which should resolve this for you) via `pip install micropy-cli --upgrade --pre`).
See #288 #293 #289 for more details. 

Please let me know if you still have issues. Thanks!
