### ISSUE TITLE
Error: StopIteration - Click library

### ISSUE THREAD

**Issue by redghc** [BradenM/micropy-cli#300]
**Describe the bug**
Get an error when trying to generate stubs

**Expected Behavior**
Stubs are generated

**Current Behavior**
![imagen](https://user-images.githubusercontent.com/94464560/167742321-1bf834b5-45c3-4238-85b0-255c1ac24b7a.png)

**Steps to Reproduce**
1. Install micropy-cli 4.0.0rc2 
2. Connect esp32 with Micropython v.1.18
3. Execute `micropy stubs create /dev/ttyUSB0`
4. Get error

**Logs**

> micropy stubs create /dev/ttyUSB0
> MicroPy  Connecting to Pyboard @ /dev/ttyUSB0
> MicroPy  ✔ Connected!
> Original length : 23816
> Minified length : 8338
> Reduced by      : 15478 
> MicroPy  Executing stubber on pyboard...
> MicroPy  Pyboard  Writing /createstubs.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| [8.14k/8.14k @ 2.05kB/s]
> MicroPy  ✔ Done!
> MicroPy  Copying stubs...
> Traceback (most recent call last):
>   File "/home/red/.pyenv/versions/3.9.12/bin/micropy", line 8, in <module>
>     sys.exit(cli())
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/micropy/cli.py", line 277, in create
>     return mpy.create_stubs(port, verbose=verbose)
>   File "/home/red/.pyenv/versions/3.9.12/lib/python3.9/site-packages/micropy/main.py", line 132, in create_stubs
>     stub_path = next(out_dir.iterdir())
> StopIteration

**Context (Environment)**
OS: Arch Linux x86_64
Kernel: 5.17.5-arch1-1
MicroPy-cli 4.0.0rc2
Python 3.9.12
PIP 22.0.4

**Comment by redghc** [comment]
Found this issue
https://github.com/BradenM/micropy-cli/issues/47

Delete de /flash folder existing in esp32, now all is OK.
