### ISSUE TITLE
BUG: TypeError: Unknown color 'bright_green'

### ISSUE THREAD

**Issue by patvdleer** [BradenM/micropy-cli#40]
```
$ micropy --version
micropy, version 2.0.1
```

```
$ micropy init
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/click/termui.py", line 372, in style
    bits.append('\033[%dm' % (_ansi_colors.index(fg) + 30))
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/micropy", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/micropy/cli.py", line 63, in init
    mp = MicroPy()
  File "/usr/local/lib/python3.7/dist-packages/micropy/main.py", line 26, in __init__
    self.setup()
  File "/usr/local/lib/python3.7/dist-packages/micropy/main.py", line 30, in setup
    self.log.debug("\n---- MicropyCLI Session ----")
  File "/usr/local/lib/python3.7/dist-packages/micropy/logger.py", line 274, in debug
    return self.debug(msg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/micropy/logger.py", line 275, in debug
    self.echo(msg, log="debug")
  File "/usr/local/lib/python3.7/dist-packages/micropy/logger.py", line 164, in echo
    service_title = self.get_service(fg=title_color, bold=title_bold)
  File "/usr/local/lib/python3.7/dist-packages/micropy/logger.py", line 135, in get_service
    f"{self.service_name}", fg=color, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/termui.py", line 374, in style
    raise TypeError('Unknown color %r' % fg)
TypeError: Unknown color 'bright_green'
```

```
$ sudo -H pip3.7 install -U micropy-cli
Requirement already up-to-date: micropy-cli in /usr/local/lib/python3.7/dist-packages (2.0.1)
Requirement already satisfied, skipping upgrade: click in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (6.7)
Requirement already satisfied, skipping upgrade: jinja2 in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (2.10)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (2.22.0)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (19.1)
Requirement already satisfied, skipping upgrade: rshell in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (0.0.26)
Requirement already satisfied, skipping upgrade: requirements-parser in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (0.2.0)
Requirement already satisfied, skipping upgrade: jsonschema in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (3.0.2)
Requirement already satisfied, skipping upgrade: tqdm in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (4.24.0)
Requirement already satisfied, skipping upgrade: questionary in /usr/local/lib/python3.7/dist-packages (from micropy-cli) (1.2.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2->micropy-cli) (1.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->micropy-cli) (2018.1.18)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->micropy-cli) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests->micropy-cli) (2.6)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->micropy-cli) (1.22)
Requirement already satisfied, skipping upgrade: attrs in /usr/local/lib/python3.7/dist-packages (from packaging->micropy-cli) (19.1.0)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.7/dist-packages (from packaging->micropy-cli) (1.11.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages/pyparsing-2.2.0-py3.7.egg (from packaging->micropy-cli) (2.2.0)
Requirement already satisfied, skipping upgrade: pyudev>=0.16 in /usr/local/lib/python3.7/dist-packages (from rshell->micropy-cli) (0.21.0)
Requirement already satisfied, skipping upgrade: pyserial in /usr/local/lib/python3.7/dist-packages (from rshell->micropy-cli) (3.4)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.7/dist-packages (from jsonschema->micropy-cli) (40.0.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema->micropy-cli) (0.15.4)
Requirement already satisfied, skipping upgrade: prompt-toolkit~=2.0 in /usr/local/lib/python3.7/dist-packages (from questionary->micropy-cli) (2.0.9)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/python3.7/dist-packages/wcwidth-0.1.7-py3.7.egg (from prompt-toolkit~=2.0->questionary->micropy-cli) (0.1.7)
```

**Comment by patvdleer** [comment]
You need to add click to the requirements, `click >=7`

**Comment by BradenM** [comment]
Hi @patvdleer, thanks for the report! 

Just tested this out and found that you are correct! I will update the click requirement soon. Thanks!
