### ISSUE TITLE
failed to execute micropy-cli on windows 10

### ISSUE THREAD

**Issue by jtuttas** [BradenM/micropy-cli#41]
Hello, just try to execute the micropy cli on windows 10 with the command "micropy stubs search esp32" and i've got the following stack trace

```
Traceback (most recent call last):
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jtutt\AppData\Local\Programs\Python\Python36-32\Scripts\micropy.exe\__main__.py", line 5, in <module>
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\site-packages\micropy\cli.py", line 13, in <module>
    from micropy.main import MicroPy
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\site-packages\micropy\main.py", line 9, in <module>
    from micropy import data, utils
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\site-packages\micropy\utils\__init__.py", line 12, in <module>
    from .pybwrapper import PyboardWrapper
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\site-packages\micropy\utils\pybwrapper.py", line 14, in <module>
    import rshell.main as rsh
  File "c:\users\jtutt\appdata\local\programs\python\python36-32\lib\site-packages\rshell\main.py", line 67, in <module>
    if 'libedit' in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable
```

Did you have any idea what is going wrong?

best regards

jtutt

**Comment by jtuttas** [comment]
Ah, after updating to the latest version of python 3.7.4. it works !
