### ISSUE TITLE
micropy-cli syntax problem ? (i am not sure)

### ISSUE THREAD

**Issue by alichbouki** [BradenM/micropy-cli#524]
Hi, I just discovered this amazing tool as i want to start using my raspberry pi pico with micropy-cli
ii jest installed it as described in the README file:
`pip install micropy-cli --upgrade`
The installation went well, but as i want to create a project
`micropy init myproject`
It crashes with this error message:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\micropy.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\micropy\app\__init__.py", line 1, in <module>
    from .main import app
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\micropy\app\main.py", line 16, in <module>
    from .stubs import stubs_app
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\micropy\app\stubs.py", line 21, in <module>
    from micropy.pyd.backend_rshell import RShellPyDeviceBackend
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\micropy\pyd\backend_rshell.py", line 30, in <module>
    import rshell.main as rsh  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\rshell\main.py", line 80, in <module>
    import readline
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
         ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

The tricky part is that i am using a windows 10 as my main OS, as i switch to use WSL2 with Ubuntu it works just fine
Please help me i need to use it so badly

**Comment by BradenM** [comment]
@alichbouki

Hi, the issue you are running into here is not related to micropy-cli but due to a windows specific issue relating to pyreadline due to a change post python 3.9.

See: https://github.com/pyreadline/pyreadline/issues/65

If I recall correctly, you probably need to remove pyreadline and install pyreadline3.

`pip uninstall pyreadline && pip install pyreadline3`
