### ISSUE TITLE
micropy init fails on Win10

### ISSUE THREAD

**Issue by Lars-O-Knudsen** [BradenM/micropy-cli#59]
I installed your awesome micropy-cli on Windows 10  following LeMaRiva’s guide and your readme.
Installation and stub creation went fine. 

But ”micropy init” fails as seen below.
(I have different problems when I try to run the cmd in a folder on my NAS shared drive  – but thats another story and not important right now)

VSCode is in my path and I can launch it from the cmd line.

**VSCODE version info:**
Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Python**: 3.7.4,

**VS Code extension**:
Name: Python
Id: ms-python.python
Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
Version: 2019.10.41019
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python

I hope you can help me out.

Thanks,

Lars Østergaard Knudsen
Copenhagen, Denmark

C:\Users\famil\Documents\Projects\MicroPython>micropy init hello1

MicroPy  Creating New Project
? Choose any Templates to Generate  [VSCode Settings for Autocompletion/Intellisense]
? Which stubs would you like to use?  [esp32-micropython-1.11.0]

MicroPy  Initiating hello1
MicroPy  Stubs: esp32-micropython-1.11.0

MicroPy  Rendering Templates
MicroPy  Populating Stub info...
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\micropy.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\micropy\cli.py", line 97, in init
    proj_relative = project.create()
  File "c:\program files\python37\lib\site-packages\micropy\project\project.py", line 364, in create
    self.render_all()
  File "c:\program files\python37\lib\site-packages\micropy\project\project.py", line 343, in render_all
    self.provider.render_to(t, self.path, **self.context)
  File "c:\program files\python37\lib\site-packages\micropy\project\template.py", line 256, in render_to
    template.run_checks()
  File "c:\program files\python37\lib\site-packages\micropy\project\template.py", line 60, in run_checks
    results = [not ck() for ck in self.CHECKS]
  File "c:\program files\python37\lib\site-packages\micropy\project\template.py", line 60, in <listcomp>
    results = [not ck() for ck in self.CHECKS]
  File "c:\program files\python37\lib\site-packages\micropy\project\checks.py", line 47, in vscode_ext_min_version
    name, vers = next(iter_vscode_ext(name=ext), (ext, '0.0.0'))
  File "c:\program files\python37\lib\site-packages\micropy\project\checks.py", line 24, in iter_vscode_ext
    proc = subproc.run(_cmd.split(), text=True, capture_output=True)
  File "c:\program files\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\program files\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\program files\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Den angivne fil blev ikke fundet

**Comment by BradenM** [comment]
Hi @Lars-O-Knudsen,

Thanks again for reaching out. I apologize for taking a bit longer then I had stated in my email, but this issue has now been fixed. The patch will be included in the next release, but you can simply install `micropy-cli` from git if you wish to use it immediately.

Thanks!
